name: make

on: workflow_dispatch

env:
  URL_MINIZ: https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make miniz busyz URL_MINIZ=$URL_MINIZ

      - name: test
        run: cd .. && ./busyz/busyz zip -r -x busyz/.git -x busyz/miniz.c -x busyzip/minizip.h archive.zip busyz && unzip archive.zip

