name: make

on: workflow_dispatch

env:
  URL_MINIZ: https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip
  MAKEFLAGS: -j2

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make miniz nanozip URL_MINIZ=$URL_MINIZ

      - name: test
        run: ./nanozip -r -x miniz.c -x minizip.h ../archive.zip $PWD && unzip ../archive.zip

