name: make

on: workflow_dispatch

env:
  URL_MINIZ: https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make miniz busyz URL_MINIZ=$URL_MINIZ

      - name: test
        run: cd .. && ./busyz/busyz zip -r archive.zip busyz -x busyz/.git -x busyz/miniz.c -x busyz/minizip.h && mkdir busyz/archive && mv archive.zip busyz/archive && cd busyz/archive && unzip archive.zip
      
      - uses: actions/upload-artifact@v4
        with:
          path: archive.zip
